name: 'Install System Tools and Dependencies'

runs:
  using: "composite"
  steps:
    - name: Restore cache
      id: cache-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          /var/cache/apt/
          $HOME/.cargo
        key: sysdeps

    - name: Update APT Cache
      run: sudo apt-get update
      shell: bash

    - name: Install System Tools
      run: sudo apt-get install -y build-essential clang lld pkg-config zstd curl
      shell: bash

    - name: Install System Libraries
      run: sudo apt-get install seccomp libseccomp-dev
      shell: bash

    - name: Install Buck2
      run: |
        curl https://github.com/facebook/buck2/releases/download/latest/buck2-x86_64-unknown-linux-gnu.zst --output "${{runner.temp}}/buck2-x86_64-unknown-linux-gnu.zst" --location --silent --show-error --fail --retry 5
        zstd -d "${{runner.temp}}/buck2-x86_64-unknown-linux-gnu.zst" -o $HOME/.cargo/bin/buck2
        chmod +x $HOME/.cargo/bin/buck2
        rm -f "${{runner.temp}}/buck2-x86_64-unknown-linux-gnu.zst"
      shell: bash

    - name: Install Reindeer
      run: cargo install --locked --git https://github.com/facebookincubator/reindeer reindeer
      shell: bash

    - name: Save cache
      if: ${{ steps.cache-restore.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v4
      with:
        path: |
          /var/cache/apt/
          $HOME/.cargo
        key: sysdeps
